### PR TITLE
Added Bag Toss Count screen.

### PR DESCRIPTION
**Pull request by MattiasBuelens**
May help to come up with toss-safe bag coordinates. Although it's kind of hard, since the clickable thrash count takes up so much space...

### CODE REVIEW

**Comment by hftf** [comment]
Did you rename the other image?

**Comment by MattiasBuelens** [comment]
No, that's still just called "Bag toss". I guess I can name it "Bag toss confirm" or something, but then it gets quite long...

Perhaps I should just rename them both to "Toss count" and "Toss confirm" and drop the bag prefix? It's not like you can toss anything in any other screen.

**Comment by MattiasBuelens** [comment]
How about this?

**Comment by hftf** [comment]
Ah sorry! I only saw the case change in `data.js` from `Bag Toss` to `Bag toss` (in the first commit) and assumed the image wasn't moved from `Bag Toss.png` to `Bag toss.png` — the inconsistency was actually in #16 but you had fixed it here. My mistake!

Either way I guess I prefer "Trash" because it looks like that's what the menu item is called.

**Pull request merged**
