### PR TITLE
State refactor

### LINKED ISSUE #31: Update overlaps when a checkbox is clicked

### PR DESCRIPTION
**Pull request by MattiasBuelens**
Refactored `State` to better handle changes.
- Internal `_State` methods don't do external updates.
- Public `State` methods wrap internal methods to trigger external updates at the end of the call.
- External uses of `State` methods are reduced so each change can be fully handled by one single `State` call, thus only triggering updates once.

This also fixes #31, since now `rotateState` triggers the correct updates.

### CODE REVIEW

**Comment by hftf** [comment]
Looks great. I suppose we don’t really need the currying stuff anymore.

**Comment by MattiasBuelens** [comment]
True, the currying for `setState` could be removed without much effort.

`rotateState` and `rotateStates` are a bit trickier, since they both use the `State` and the DOM element objects and only one of those can be the `this` context. We should probably make it accept the element(s) as parameter and change the event handler binding.

**Comment by hftf** [comment]
Done — see d926258.

**Comment by MattiasBuelens** [comment]
Went a bit more in depth in #47. :wink:

**Pull request merged**
