### PR TITLE
Added variability region.

### PR DESCRIPTION
**Pull request by MattiasBuelens**
- Variability is displayed on a separate canvas layer.
- If the current coordinate hits one or more buttons which should be avoided, those buttons are drawn with a red highlight to indicate the error.
- If the current coordinate hits one or more buttons which should be clicked, the _intersection_ of all these buttons is drawn with a green highlight to show the variability of the coordinate. All buttons which should be avoided are removed from the intersection.

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
I went with my interpretation on what variability should incorporate. If you had something (slightly) different in mind, feel free to elaborate. :smiley:

**Comment by hftf** [comment]
I like it, but I swear the feature seemed more… “useful” in my head. (Actually I started implementing this locally yesterday, except inside of `list_overlaps` to minimize code duplication.)

We probably should fix #31 – Update overlaps when a checkbox (or the example scenario) is clicked.

**Comment by MattiasBuelens** [comment]
I started in `list_overlaps` first as well, but then I ended up with a lot of variables in that function and I just pulled it into a separate function.

I had a look at #31 too while working on this, see [my comment on that issue](https://github.com/hftf/coords/issues/31#issuecomment-48514511).

**Comment by hftf** [comment]
- Originally the issue was not being able to see buttons’ boundaries at a glance.
- This feature displays the boundaries upon clicking.

Now that I played with it a little, I’m kind of questioning why I thought this feature should even be “interactive.” It seems like somewhat of a wasted opportunity to make clicking on the canvas more “usefully” interactive (no good ideas yet, though).

What are the pros and cons of:
- Drawing the buttons as green/red with some kind of outline, instead of blue/erase as currently?
  Maybe something like a [“tint band”](https://www.mapbox.com/blog/customizing-geography-class/) used on maps.
- Doing this, but on hover instead of on click?

**Comment by hftf** [comment]
Merged in 75b50e1

**Pull request closed without merging**
