### PR TITLE
Triple battle.

### PR DESCRIPTION
**Pull request by MattiasBuelens**
- Original Fight screen renamed to Rotation battle.
- New Fight screen with Shift button for Triple battles.
- Added Triple battle target selection.

### CODE REVIEW

**Comment by hftf** [comment]
Are the refs correct? Does Triple Battle → Cancel (id `btx`) really go to Rotation Battle (id `br`)?

I've never used Rotation or Triple battles, so I'd have to trust you here, but it seems a bit off to me.

Also, how should we deal with there not being a directed edge from Battle to Rotation Battle?

**Comment by MattiasBuelens** [comment]
That was an error indeed, fixed now! :smiley: 

I don't really see a good solution for that edge. The alternative would be combining the Battle and Rotation battle screens, but that would cause overlap between the Shift and Rotate buttons...

**Comment by hftf** [comment]
Isn't `br1..br4` → `bt` also incorrect? (Also I'd prefer if you put fixes in a new commit so that I can easily merge or see a diff, instead of amending the old commit.)

---

I see only two solutions:

```
"Fight":            { "id": "f", "coords": [  0,  23,   255, 143], "ref": "bf"  },
"Fight (rotation)": { "id": "F", "coords": [  0,  23,   255, 143], "ref": "br"  },
```

or

```
"Fight":            { "id": "f", "coords": [  0,  23,   255, 143], "ref": ["bf", "br"]  },
```

<del>IMO combining screens so that they have overlapping buttons is more of a problem.</del> The disadvantage of combining screens is that it breaks "one screenshot per screen".

**Comment by MattiasBuelens** [comment]
It depends on what you still want to do with those refs. If it's just for making graphs, then the second solution is sufficient and more elegant. If you later want to implement links next to a button to jump to the referred screen, then having multiple refs for one button will be problematic.

Side note: I think there are still 2 screens with overlapping buttons. Overworld Options and Misc Starters. Do you think we should split these?

**Comment by hftf** [comment]
Yeah, I'm still figuring out what I want to do with them. I doubt the graph library supports hyperedges anyway (since, a button is an edge from its parent screen to its ref screen, having multiple refs actually makes it a hyperedge).

If you think it's worth the effort to split those and make new screenshots, go ahead and make a PR :wink:

**Pull request merged**
