### PR TITLE
Bunch of fixes and extras.

### PR DESCRIPTION
**Pull request by MattiasBuelens**
- Added screen and coordinates for move selection when teaching a TM/HM.
- Added screen and coordinates for Pokémon menu (Summary/Move/Item/HMs).
- Added screen and coordinates for PokéGear and phone.
- Added screens for fly maps. Ccoordinates aren't useful here, as the fly map pans horizontally depending on the player's location.

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
Not sure if this will still be useful, but I thought I'd help fix some stuff and add some extra screens which we may still need to use (switch party around, teach Rock Climb,...).

**Comment by hftf** [comment]
Can you fix the typos (“Jotho” → “Johto”) and split the CSS changes to a separate pull request?

---

To consider:
- Move the Pokégear screens to a separate Pokégear category if you plan to add a lot more Pokégear screens
- Make the wording/capitalization consistent (“Scroll Up” → “Up”, “HM Move 1” → “Move 1”, “PokéGear” → “Pokégear”)

(Note: “PC Misc” is intended to be just a temporary catch-all “screen” until the rest of the PC screens are added, so I wouldn’t worry too much about the rename.)

**Comment by MattiasBuelens** [comment]
Damnit, I always get "Johto" wrong. Anyway, fixed!

It simply bothered me that the PC Misc screen had no image and thus showed an "image not found" placeholder. I don't think we'll need extra screens for the PC though, we don't want to help the trolls. :stuck_out_tongue:

**Comment by hftf** [comment]
Looks good, I'll merge it when the CSS is reverted.

But I am a troll! :frowning:

**Comment by MattiasBuelens** [comment]
What's with the CSS? You'd rather have the image show up on hover than have it always there but transparent?

**Comment by hftf** [comment]
I just prefer pull requests to be as atomic as possible. :bookmark_tabs: I think any CSS changes should be discussed/committed/merged separately from screen additions/changes.

**Comment by MattiasBuelens** [comment]
Fair point. I'll make a separate pull request for one small CSS bugfix.

**Pull request merged**
