### PR TITLE
Fix checkbox alignment in headings.

### PR DESCRIPTION
**Pull request by MattiasBuelens**
Checkbox currently overlaps the heading when the title gets longer. This should fix that by floating the checkbox instead of absolutely positioning it.

Before and after:
Before and after

### CODE REVIEW

**Comment by hftf** [comment]
Hmm, this fix only gives 1 em of leeway (or 2 em of centered text) before the label overflows regardless :confused: — yet it comes at the expense of the label being noticeably off-center.

Any suggestions for a more clever solution? Perhaps only displaying the checkbox on hover?

**Comment by MattiasBuelens** [comment]
I guess you could simply fix the width of `.menu-heading` so the text in the `h3` wraps:

``` css
.menu-heading {
    width: 128px; /* Same as .menu-heading .layers */
}
```

**Comment by hftf** [comment]
Obsoleted by b6688d1

**Comment by MattiasBuelens** [comment]
That's a much nicer fix indeed! :smiley:

**Comment by hftf** [comment]
Unfortunately it breaks stuff; see #62

**Pull request closed without merging**
