### PR TITLE
Removed currying from State.setState.

### PR DESCRIPTION
**Pull request by MattiasBuelens**
Turns out we don't even need the currying for the `map` parameter, we can just pass the `state.checked` and `state.indeterminate` arrays as argument. :stuck_out_tongue: I just removed the curry helper altogether.

Made `rotateState(s)` accept the DOM element as parameter. This puts it in line with the `setState` signature and makes it easier to work with.

### CODE REVIEW

**Comment by hftf** [comment]
Ahhh that’s too bad we removed the <code>_State.setState._state_</code> functions, I was going to split up the `setState` method like this :stuck_out_tongue_closed_eyes: 

```
setStates: function(state, els) {
    return Array.prototype.map.call(els, this.setState[state]);
},
```

**Comment by MattiasBuelens** [comment]
I don't really like adding properties to a function, i.e. `setState.checked`. Although I agree that perhaps the handling of arrays can be moved outside of `setState` and let `setState` only deal with a single ID or element as input.

**Comment by hftf** [comment]
How about d10aa37? Would be nicer without that silly for loop :stuck_out_tongue:

**Comment by MattiasBuelens** [comment]
Sure, that works too.

**Pull request merged**
