### PR TITLE
X: New screenshots

### PR DESCRIPTION
**Pull request by MattiasBuelens**
Added screenshots for new screens in Pokémon X/Y.

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
Erm, this PR only has screenshots though. It's still very much a WIP, no coordinates or anything yet. :stuck_out_tongue:

**Comment by hftf** [comment]
Merging #70 closed this one automatically.

**Comment by MattiasBuelens** [comment]
Oh great, GitHub was too greedy. :stuck_out_tongue: All right, I'll just open a new PR then.

**Comment by hftf** [comment]
- [ ] `PC › PC` a button seems to be missing
- [ ] `PC › Box` cancel and quit missing
- [ ] `PC › Deposit` and `PC › Withdraw` have extra cancel and quit buttons that are not in screenshot

**Comment by MattiasBuelens** [comment]
Actually, the problem is that the `PC > PC` screenshot made by the 3DS streamer was taken **after** beating the Elite Four. Before you beat the E4, there is no Records option in the PC. The coordinates are adjusted for this, but the screenshot is not.

The Deposit and Withdraw screens are indeed a bit misleading, they actually both consist of two states: with or without a Pokémon selected. When a Pokémon is selected, the right-hand menu shows up and blocks the Cancel and Exit PC buttons. When no Pokémon is selected, the right-hand menu is hidden and those two buttons are available again.

Either way, I agree that it's probably less confusing to just move those buttons to the `PC > Box` screen. See #72.

**Comment by hftf** [comment]
I believe there's (possibly) another screen with two states conflated into one screenshot: `Overworld › Pokémon Do`. So optimally for `PC › Deposit`, `PC › Withdraw`, and `Overworld › Pokémon Do` we would have another screen for the missing state.

**Comment by MattiasBuelens** [comment]
Correct, you have to hit "Use a move" before that extra menu shows up. Although in this case I'm not sure if you can or cannot hit a button like "Summary" when you've already clicked "Use a move". If you can, it would make sense to keep them on one screen.

I'm not sure how we should handle these cases. On the one hand, more screens with more references would make it more clear what buttons need to be pressed and how the screens relate to each other. On the other hand, having too much screens makes it hard to keep track of what you're doing, having to navigate and scroll through a bunch of screens to get everything set up.

**Comment by hftf** [comment]
For now, aim for accuracy with refs as much as possible, but ignore these few cases of conflated screens until the layout is fixed (#73).

**Comment by MattiasBuelens** [comment]
Agreed. Navigation is just awkward in general, better postpone this issue until after the layout redesign.

**Comment by hftf** [comment]
> I believe there's (possibly) another screen with two states conflated into one screenshot: `Overworld › Pokémon Do`.

Found it, fwiw: http://imgur.com/a/tLfOx#rL066a6

**Pull request merged**
